### ISSUE TITLE
EOL Versions

### ISSUE THREAD

**Issue by loganbush789** [dom4j/dom4j#115]
I am trying to figure out what versions of dom4j are EOL, and if so, when do these versions become EOL?

**Comment by ecki** [comment]
Dom4j is a slow moving small project with now active branches, so I would only consider the last version as supported (or EOL :).

Having said that you might get help on older versions and even patches, but you also might not get any help on even the most recent version. Typically you would only get fixed versions based on the next release of the main branch.

 With open source you always get what you pay for. But then again, I am in no official function in the project, just speaking out of experience.

**Comment by FilipJirsak** [comment]
Live versions of dom4j are 2.0.3 and 2.1.3. Version 2.1.3 is considered the current version. Version 2.0.3 is maintained to support Java older than 8. No official EOL for 2.0.3 is specified, but only security updates can be expected. Security patches for version 1.6.1 may be released in case of severe security bugs.
