### ISSUE TITLE
How to use org.dom4j.io.SAXWriter.parse(org.xml.sax.InputSource input)? It only accepts DocumentInputSource, which is not a public class.

### ISSUE THREAD

**Issue by allomy** [dom4j/dom4j#127]
From the source code, the `org.dom4j.io.SAXWriter.parse` method only accepts the parameter `DocumentInputSource`(source code linkage: https://github.com/dom4j/dom4j/blob/version-2.1.3/src/main/java/org/dom4j/io/SAXWriter.java#L599), however the `DocumentInputSource` is not a public class(source code linkage: https://github.com/dom4j/dom4j/blob/version-2.1.3/src/main/java/org/dom4j/io/DocumentInputSource.java#L28). I'm confused about how to use this `parse` method, is it for inner usage? Or the DocumentInputSource needs to be a `public` class?
```
public class SAXWriter implements XMLReader {
    public void parse(InputSource input) throws SAXException {
        if (input instanceof DocumentInputSource) {
            DocumentInputSource documentInput = (DocumentInputSource) input;
            Document document = documentInput.getDocument();
            write(document);
        } else {
            throw new SAXNotSupportedException(
                    "This XMLReader can only accept "
                            + "<dom4j> InputSource objects");
        }
    }
}
```
```
class DocumentInputSource extends InputSource {
...
}
```

**Comment by FilipJirsak** [comment]
It is only for inner usage. It doesn't make sense to use it from custom code.

**Comment by allomy** [comment]
Thank you for your reply, Filip.
