### ISSUE TITLE
Keep duplicate namespaces parent-child-tags

### ISSUE THREAD

**Issue by pellerito** [dom4j/dom4j#128]
How can i accept duplicate namespaces? I want that the namespaces from my dc:records (parent-tag) are kept in my dc:record (child-tag) too. Now the duplicates are removed, if i print out the document. How can i avoid this bevavior?

Original xml:
<dc:records xmlns:dc="http://pur.org/dc/elements/1.1/" xmlns:dcterms="http://pur.org/dc/terms/">
           <dc:record xmlns:dc="http://pur.org/dc/elements/1.1/" xmlns:oai_dc="http://www.archives.org/OAI/2.0/oai_dc/" 
              xmlns:dcterms="http://pur.org/dc/terms/">

After printing out (what i dont want):
<dc:records xmlns:dc="http://pur.org/dc/elements/1.1/" xmlns:dcterms="http://pur.org/dc/terms/">
           <dc:record xmlns:oai_dc="http://www.archives.org/OAI/2.0/oai_dc/">

Wished printing:
Like original xml

Thanks

**Comment by FilipJirsak** [comment]
You can use `Element.addNamespace(String, String)` or `Element.add(Namespace)` to add namespace to your element. But standard `org.dom4j.io.XMLWriter` keeps a stack of namespaces so it will not print the duplicate namespace again. You can extend `XMLWriter` and override the appropriate methods.

**Comment by pellerito** [comment]
Extending XMLWriter and removing NamespaceStack was the solution. Thank you for the idea, Filip!
