### ISSUE TITLE
about Upgrade from dom4j 1.x to the latest version 2.1.3

### ISSUE THREAD

**Issue by qianliniu** [dom4j/dom4j#136]
Hi
We have a old maintenance project, still using dom4j 1.4.
and we want to upgrade to the latest version 2.1.3, 
 is there any interfaces different between the 1.x and 2.1.3?
 does the program need any code modification, or only simply change the version like below is enough? Thanks.
current:
```
<dependency>
    <groupId>dom4j</groupId>
    <artifactId>dom4j</artifactId>
    <version>1.4</version>
</dependency>
```
 
new:
```
<dependency>
    <groupId>org.dom4j</groupId>
    <artifactId>dom4j</artifactId>
    <version>2.1.3</version>
</dependency>
```

**Comment by FilipJirsak** [comment]
There are no significant changes in interfaces between versions 1.6.1 and 2.1.3. If you use `dom4j` in the usual way, just change the version number (and `groupId`).
