### ISSUE TITLE
dom4j-2.1.3-javadoc don't work

### ISSUE THREAD

**Issue by moxbbzz** [dom4j/dom4j#138]
There is a problem with the search function.
 When I search SAXReader, the page will jump to 
dom4j-2.1.3-javadoc/undefined/org/dom4j/io/SAXReader.html
But the right page is
dom4j-2.1.3-javadoc/org/dom4j/io/SAXReader.html

![pic1](https://user-images.githubusercontent.com/97511362/148913977-b04d95bb-2b1e-4c07-ab53-2691ce003a62.png)
![pic](https://user-images.githubusercontent.com/97511362/148913748-a76fde4c-958f-443e-a160-ada797909656.png)

**Comment by FilipJirsak** [comment]
There is no search field in the published documentation on dom4j.github.io (https://dom4j.github.io/javadoc/2.1.4/).
