### ISSUE TITLE
The file is occupied and cannot be deleted

### ISSUE THREAD

**Issue by lfift** [dom4j/dom4j#139]
Version: 2.1.3
When I read the XML file using SAXReader, I found that the file was still occupied even though I had closed the stream.The following code.
InputStream is = null;
        try {
            is = OfdRwController.class.getClassLoader().getResourceAsStream("test.xml");
            assert is != null;
            Document read = SAXReader.createDefault().read(is);
            System.out.println(read.getRootElement().getName());
        } catch (Throwable throwable) {
            throwable.printStackTrace();
        } finally {
            try {
                assert is != null;
                is.close();
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
![image](https://user-images.githubusercontent.com/31279478/149159228-63e6dcdb-4c79-4cad-9535-8d60baa8bb1d.png)
I tried to solve the problem using File-Leak-Detector but couldn't find it.
![image](https://user-images.githubusercontent.com/31279478/149160005-a7fb4e18-8b54-4000-83e4-f27c89b7c645.png)

**Comment by FilipJirsak** [comment]
Wich file is occupied? You read the XML file from classpath, co probably from some JAR file. I think the JAR file remains opened by the classloader.
