### ISSUE TITLE
DTD is not handled properly

### ISSUE THREAD

**Issue by hosijyun** [dom4j/dom4j#140]
The XML below should be correct. I think dom4j didn't handle the [ExternalID](https://www.w3.org/TR/xml/#NT-ExternalID) well.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE note PUBLIC "-//DTD NOTE 1.0//EN" "http://www.example.com/note.dtd">
<note>
</note>
```

**Comment by FilipJirsak** [comment]
dom4j does not parse XML sources. It uses a user-specified parser to do this, usually SAX. By default, the parser is configured to block external entities (for security reasons). However, it is possible to configure the parser as you wish. You can set preconfigured SAX parser with [SAXReader(XMLReader)](https://dom4j.github.io/javadoc/2.1.3/org/dom4j/io/SAXReader.html#SAXReader-org.xml.sax.XMLReader-boolean-) constructor. Or you can set SAX parser configuration with SAXReader's [`setXXX`](url) methods.
