### ISSUE TITLE
Element#element("xx")偶尔会报空指针，偶尔又是正常的

### ISSUE THREAD

**Issue by hungryforit** [dom4j/dom4j#143]
`// 获取请求报文模板
		Document documentForHKSmartListRequestXmlMappingXml = HKConfigPOJO.getDocumentForHKSmartListRequestXmlMappingXml();
		Log.debug(documentForHKSmartListRequestXmlMappingXml.toString());

		// 基于模板填充真实报文
		Element rootElement = documentForHKSmartListRequestXmlMappingXml.getRootElement();
		Log.debug(rootElement.toString());

			// 填充SYS_HEAD
		Element sysHeadElement = rootElement.element("SYS_HEAD");
		Log.debug(sysHeadElement.toString());
		
		Element consumerSeqNoElement = sysHeadElement.element("CONSUMER_SEQ_NO"); // 【看这里：偶尔会报错空指针】
		String consumerSeqNo = UUIDUtil.randomUUID();
		consumerSeqNoElement.setText(consumerSeqNo);

		Element tranDateElement = sysHeadElement.element("TRAN_DATE"); // 【看这里：偶尔会报错空指针】
		String tranDate = TimeUtil.getNowYYMMDD();
		tranDateElement.setText(tranDate);

		Element tranTimestampElement = sysHeadElement.element("TRAN_TIMESTAMP"); // 【看这里：偶尔会报错空指针】
		String tranTimestamp = TimeUtil.getNowHHMMSSsss();
		tranTimestampElement.setText(tranTimestamp);

        // 填充BODY
		Element bodyElement = rootElement.element("BODY");
		Element globalIdElement = bodyElement.element("GLOBAL_ID");
		globalIdElement.setText(idNo);`

补充：上边有三行sysHeadElement.element("xxx")，项目稳定运行一段时间后，有时候就会报空指针，还不一定报错到这三行代码的哪一行上。

**Comment by FilipJirsak** [comment]
Please use English for bug reports.
