### ISSUE TITLE
XPath contains function not working

### ISSUE THREAD

**Issue by maddin79** [dom4j/dom4j#153]
Hello,

I'm trying to get specific nodes from a XML document with selectNodes() function and XPath. I tested my XPath with several XPath validators and it is correct. But with dom4j i never get the nodes. 

The XML has kind of the following structure:
```
<document>
    <node>
        <meta>
            <id>A 1</id>
        </meta>
        <text>some text</text>
    </node>
    <node>
        <meta>
            <id>B 1</id>
        </meta>
        <text>some text</text>
    </node>
    <node>
        <meta>
            <id>A 2</id>
        </meta>
        <text>some text</text>
    </node>
</document>
```

I have 3 XPath expressions that are working with XPath validators:

`/document/node[meta/id[contains(., 'A')]]`
`/document/node[meta/id[contains(text(), 'A')]]`
`/document/node[meta/id[text()[contains(., 'A')]]]`

With dom4j this is not working. I never get any nodes. If I use only `/document/node[meta/id]` I get every node with the meta/id tag. I can not find any solution to this online. Any help or hint is highly appreciated. 

Best
Martin

**Comment by Boris-de** [comment]
All of them seem to work for me. Just on as an example:

```java
    DocumentHelper.parseText("<document>\n" +
                               "  <node><meta><id>A 1</id></meta><text>some text</text></node>\n" +
                               "  <node><meta><id>B 1</id></meta><text>some text</text></node>\n" +
                               "  <node><meta><id>A 2</id></meta><text>some text</text></node>\n" +
                               "</document>")
      .selectNodes("/document/node[meta/id[contains(., 'A')]]").stream()
      .map(it -> it.selectSingleNode("meta/id").getText())
      .forEach(System.out::println);
```
outputs
```text
A 1
A 2
```
for me (I just removed some whitespace to reduce the size of the example. It also works with copy&paste of your example XML with all whitespace)

Does your original XML looks in any way different to your example here, perhaps it has namespaces?

**Comment by maddin79** [comment]
@Boris-de Thank you for checking. The actual XML File is much more complex and maybe it is something in that file that causes this behavior. Could not figure out what, but I found a different solution. The example I posted is indeed working. 
I close this because it seems like a file problem.
