### ISSUE TITLE
Strongly hope 2.1.4 to be released, Please Thank you.

### ISSUE THREAD

**Issue by lvgang5213** [dom4j/dom4j#155]
Dom4j is a good xml parsing software. Many of our products rely on it, but we have found that the new version of Dom4j has not been released for two years. Our products face the risk of decline and replacement of Dom4j. We really want Dom4j to stay. We hope the community can release the latest version 2.1.4, so that we can continue to use it for two years. Thank you!

**Comment by lvgang5213** [comment]
The company requires that the third-party parts that have not been updated for more than two years face the risk of recession and replacement.  So we strongly hope to newest 2.1.4 version.

**Comment by ecki** [comment]
Irmis probably best to donate some engineering hours to test the current head, to look at open bugs and documentation. The more bugs which get fixed, the more it’s worth to do a release.

**Comment by lvgang5213** [comment]
> 

Thanks very much!
