### ISSUE TITLE
How to disable escaping on certain elements?

### ISSUE THREAD

**Issue by DavidC0rtes** [dom4j/dom4j#157]
Hello, i am very new to this library and couldn't find a precise answer on how to disable escaping on certain elements.

For example i have some elements like this:
`<label>x&lt;10</label>`

But when writing it to another xml document they come out like this:
`<label>x&amp;lt;10</label>`

I would like to disable "&" escaping when adding the text `x&lt:10` to the label element.

**Comment by FilipJirsak** [comment]
Escaping cannot be disabled, it would produce invalid XML output.

Following text:
```
<label>x&lt:10</label>
```
is invalid XML input. It should be rejected by the XML parser.

If it were fixed to the correct form:
```xml
<label>x&lt;10</label>
```
The input will be correctly parsed and subsequently the `<` character will be correctly escaped during the output.

**Comment by DavidC0rtes** [comment]
> Escaping cannot be disabled, it would produce invalid XML output.
> 
> Following text:
> 
> ```
> <label>x&lt:10</label>
> ```
> 
> is invalid XML input. It should be rejected by the XML parser.
> 
> If it were fixed to the correct form:
> 
> ```
> <label>x&lt;10</label>
> ```
> 
> The input will be correctly parsed and subsequently the `<` character will be correctly escaped during the output.

Sorry that was a typo, i have `<label>x&lt:10</label>`, and when re-creating the xml document it shows like this: `<label>x&amp;lt;10</label>`

**Comment by ecki** [comment]
This is normal, if you add a & into the string value of an element it will be serialized as &amp;. If you read it back in, it will be the string you put into.

**Comment by DavidC0rtes** [comment]
yeah, i know it's normal I was just asking if such behavior could be deactivated. However, I found the method `setEscapeText` from the `XMLWriter` class that does just what I need. Thank you!
