### ISSUE TITLE
dom4j 2.1.4 Why set dependency optional to true

### ISSUE THREAD

**Issue by ouyang-xtt** [dom4j/dom4j#184]
![image](https://github.com/user-attachments/assets/6e4ae9fa-8ba9-4b83-80a9-d6909d6de5d0)
We had to proactively rely on jaxen again

**Comment by FilipJirsak** [comment]
dom4j does not require Jaxen for its basic functionality. Jaxen is only used if you want to use XPath. In that case, you need to add Jaxen as a dependency. In the future, the [library features](https://docs.gradle.org/current/userguide/feature_variants.html#feature_variants) feature of Gradle will likely be used.
