### ISSUE TITLE
org.dom4j.dom.DOMElement.setNodeValue(String)

### ISSUE THREAD

**Issue by twwwt** [dom4j/dom4j#25]
As of DOM4J 2.0.0, the implementation of the method `org.dom4j.dom.DOMElement.setNodeValue(String)` is empty. In contrast, in version 1.6.1 it calls `DOMNodeHelper.setNodeValue(this, nodeValue);`.

Is there a specific reason why it is empty or is it a bug/regression?

**Comment by FilipJirsak** [comment]
This method is empty since dom4j-1.5 - see this patch http://dom4j.cvs.sourceforge.net/viewvc/dom4j/dom4j/src/java/org/dom4j/dom/DOMElement.java?r1=1.17&r2=1.18 and related bugreport: https://sourceforge.net/p/dom4j/bugs/87/
