### ISSUE TITLE
StringIndexOutOfBoundsException in XMLWriter.writeElementContent()

### ISSUE THREAD

**Issue by marianpetras** [dom4j/dom4j#26]
If the following conditions are met:
- text-padding format is used – see OutputFormat.setPadText(boolean)
- the XML document contains a node containing a mixture of text-nodes and other nodes
- at least one of the mentioned text-nodes is empty

... then method XMLWriter.writeElementContent(Element) may throw a StringIndexOutOfBoundsException.

The cause is that the code assumes that the text of a text-node is never empty. But if the text is empty, then an attempt to get the first character fails with the exception.

A suggested patch is attached.

[patch.zip](https://github.com/dom4j/dom4j/files/1124841/patch.zip)

**Comment by marianpetras** [comment]
The StringIndexOutOfBoundsException can also be thrown in case that trimming is not enabled in the OutputFormat. This case is covered by test method XMLWriterTest.testGitHubIssue26_case7() in the pull request.

**Comment by FilipJirsak** [comment]
Merged #27
