### ISSUE TITLE
Can dom4j avoid the Man-in-the-middle attack?

### ISSUE THREAD

**Issue by john159151** [dom4j/dom4j#3]
We can use dom4j to get the xml info from a  webpage easily. Like we can use next two lines code:
" SAXReader saxReader = new SAXReader();
Document document = saxReader.read("www.google.com");// it is not the right url, just for an example "
But I wonder that can dom4j avoid the Man-in-the-middle attack? 
If it can, how? If not, do you have other way to avoid the Man-in-the-middle attack? 

looking forward to hearing from you.

**Comment by FilipJirsak** [comment]
dom4j is a library for document model only. Parsing XML file is out of its scope - you have to use some external XML parser (for example Xerces - the SAX parser bundled with JRE). Dealing with remote resources is parser responsibility. For example, you can download remote XML with HTTPS and validate the remote server certificate.
