### ISSUE TITLE
XMLWriter does not escape supplementary unicode characters correctly

### ISSUE THREAD

**Issue by abenkovskii** [dom4j/dom4j#38]
When the maximum allowed character is set to a positive value, an XMLWriter is supposed to encode any character with a Unicode code point higher then the maximum allowed character as a numeric character reference. However for supplementary Unicode characters the current implementation seams to generate a sequence of two invalid numeric character references instead of one valid.

To reproduce run:
```java
import org.dom4j.io.XMLWriter;
import org.dom4j.io.OutputFormat;
import org.dom4j.tree.DefaultElement;
import java.io.ByteArrayOutputStream;
import java.io.IOException;

class XmlBugDemo {
	public static void main(String[] arg) throws IOException {
		ByteArrayOutputStream stream = new ByteArrayOutputStream();
		OutputFormat format = OutputFormat.createPrettyPrint();
		format.setEncoding("US-ASCII");
		XMLWriter writer = new XMLWriter(stream, format);

		// this string contains a single unicode code point:
		// U+1F427 PENGUIN
		String penguin = "\ud83d\udc27";
		DefaultElement foo = new DefaultElement("foo");
		foo.addText(penguin);

		writer.write(foo);
		
		System.out.println(stream.toString("US-ASCII"));
	}
}
```

Expected result:
```xml
<foo>&#128039;</foo>
```

Actual result:
```xml
<foo>&#55357;&#56359;</foo>
```

Notes:
The actual result isn't even a well-formed xml:
```
$ xmllint bad.xml 
bad.xml:2: parser error : xmlParseCharRef: invalid xmlChar value 55357
<foo>&#55357;&#56359;</foo>
             ^
bad.xml:2: parser error : xmlParseCharRef: invalid xmlChar value 56359
<foo>&#55357;&#56359;</foo>
                     ^
```

**Comment by abenkovskii** [comment]
Here is why
```xml
<foo>&#55357;&#56359;</foo>
```
is not a well-formed xml document:
1. [xml specification section 4.1](https://www.w3.org/TR/2008/REC-xml-20081126/#dt-charref) states:
> Well-formedness constraint: Legal Character
>
> Characters referred to using character references MUST match the production for Char.

2. Char is defined in [xml specification section 2.2](https://www.w3.org/TR/2008/REC-xml-20081126/#dt-character):
> Char	   ::=   	#x9 | #xA | #xD | [#x20-#xD7FF] | [#xE000-#xFFFD] | [#x10000-#x10FFFF]	/* any Unicode character, excluding the surrogate blocks, FFFE, and FFFF. */

3. Both 55357 (0xD83D) and 56359 (0xDC27) are in surrogate blocks.

**Comment by abenkovskii** [comment]
I think this two functions are the culprit:

https://github.com/dom4j/dom4j/blob/9b141527f6715dc2f3462cb6531ed6529a5d3008/src/main/java/org/dom4j/io/XMLWriter.java#L1626-L1699

https://github.com/dom4j/dom4j/blob/9b141527f6715dc2f3462cb6531ed6529a5d3008/src/main/java/org/dom4j/io/XMLWriter.java#L1718-L1805

They encode one java char at a time rather than encoding one Unicode code point at a time.

**Comment by FilipJirsak** [comment]
Fixed.
