### ISSUE TITLE
writer.writeOpen(x) doesn't write namespaces

### ISSUE THREAD

**Issue by borissmidt** [dom4j/dom4j#39]
When i create an element with namespaces it will not write out the namespaces.
```
def writeDocument(writer: XMLWriter) 
  val rss = doc.addElement("rss")
     .addNamespace("g", "http://base.google.com/ns/1.0")
     .addNamespace("c", "http://base.google.com/cns/1.0")
   writer.writeOpen(rss)  // => doesn't work <rss>
   writer.write(rss) // => works <rss xmlns:c="http://base.google.com/ns/1.0" ... >
```
A normal write also writes out the namespaces

However when i write it using attributes it writes out the tag with namespaces.
```
def writeDocument(writer: XMLWriter) 
  val rss = XML.createElement("rss")
     .addAttribute("xmlns:g", "http://base.google.com/ns/1.0")
     .addAttribute("xmlns:c", "http://base.google.com/cns/1.0")
 writer.writeOpen(rss) // => works <rss xmlns:c="http://base.google.com/ns/1.0" ... >
```
btw it is scala code but that shouldn't matter.

**Comment by FilipJirsak** [comment]
Fixed, namespaces declared directly on an element are written out together with attributes.
Adding attributes which name starts with `xmlns` should be forbidden, but some applications depend on it so it will be fixed in version 3.0.
