### ISSUE TITLE
Missing "xsdlib" dependency in dom4j pom.xml published on Maven Central

### ISSUE THREAD

**Issue by vmassol** [dom4j/dom4j#43]
Hi guys,

I've had a problem using dom4j in some context and noticed the problem comes from the fact that dom4j's pom.xml (https://search.maven.org/remotecontent?filepath=org/dom4j/dom4j/2.1.0/dom4j-2.1.0.pom) doesn't define the `net.java.dev.msv:xsdlib:2013.6.1` dependency, which is correctly defined in `build.gradle` at https://github.com/dom4j/dom4j/blob/master/build.gradle#L28

Would be great if you could fix this for the next release! :)

Thx

**Comment by FilipJirsak** [comment]
All dependencies of dom4j are optional, so now they are marked optional in Maven pom.xml too. If you want to use some functionality which depends on `xsdlib`, you have to add runtime dependency into your project.
