### ISSUE TITLE
Different behavior on IntelliJ and Eclipse

### ISSUE THREAD

**Issue by andreasdaniel** [dom4j/dom4j#45]
I just need my issue to be answered. I run some project with dependency to dom4j. The short story is it parses some XML that its configuration was defined in some DTD.
It run perfectly on Eclipse. In the other hand, it threw some exception about undefined element on IntelliJ. All of them were exactly same except the IDE. What's the problem here? I still cannot fathom it could happen.

PS: the project also run perfectly on some CI job. I think the problem it's on IntelliJ. But, how can the same library behave differently on the same files?

**Comment by andreasdaniel** [comment]
Here is the update. Apparently it happened because somehow it couldn't recognize the XSD file. We use 2 format files, DTD and XSD. This problematic file uses XSD. How did this happen? It worked perfectly on other platform other than IntelliJ.

**Comment by FilipJirsak** [comment]
I think it is a matter of XML parser, not dom4j. Probably there is difference in runtime classpath between Eclipse, IntelliJ Idea and CI job.

**Comment by andreasdaniel** [comment]
I think you are right. Somehow the xerces wasn't active on IntelliJ. Thanks for your support.
