### ISSUE TITLE
dom4j v2 dependes on Jaxen 1.1.6 that depends on dom4j 1.6 !!

### ISSUE THREAD

**Issue by Zardoz89** [dom4j/dom4j#46]
dom4j v2 have dependencies on Jaxen 1.1.6 that depends on dom4j 1.6 

And dom4j v2 it isn't binary or source compatible with v1.6 ! Plus the dependency madness that is this.

* https://github.com/jaxen-xpath/jaxen/blob/master/pom.xml#L328
* https://github.com/dom4j/dom4j/blob/master/build.gradle#L23

**Comment by FilipJirsak** [comment]
Jaxen marked as an optional dependency.

**Comment by Zardoz89** [comment]
dom4j-2.0.3 Should have this fix. Not every body can work yet with Java 8.
