### ISSUE TITLE
Validate QName inputs

### ISSUE THREAD

**Issue by FilipJirsak** [dom4j/dom4j#48]
`QName` doesn't validate inputs, so it is possible to create `QName` for example with '<' in the tag name.

The bug was reported by @mario-areias, thanks!

**Comment by Marcono1234** [comment]
@FilipJirsak, doesn't the same issue also apply to the `uri` field?

**Comment by wilx** [comment]
Will there be a 2.0.x release with this fix? We have to support older software that has to run with Java 7 still.
