### ISSUE TITLE
dom4j-2.1.1 is not in maven central repository

### ISSUE THREAD

**Issue by xvitcoder** [dom4j/dom4j#58]
dom4j-2.1.1 and dom4j-2.0.2 are not in maven central repository.
The latest version in maven central is 1.6.1
Please add dom4j-2.1.1 to maven central

**Comment by FilipJirsak** [comment]
See https://search.maven.org/search?q=g:org.dom4j%20AND%20a:dom4j&core=gav

**Comment by xvitcoder** [comment]
Strange, I have added it into my pom file

```xml
<dependency>
    <groupId>org.dom4j</groupId>
    <artifactId>dom4j</artifactId>
    <version>2.1.1</version>
</dependency>
```
but when I do
```sh
mvn clean install
```

I get 


> [ERROR] Failed to execute goal on project xxxx: Could not resolve dependencies for project xxxx:jar:0.0.114-SNAPSHOT: Failure to find dom4j:dom4j:jar:2.1.1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced 

I tried to clean my **.m2/repository** folder, but I get the same result.
It works by the way with this dependency

```xml
<dependency>
    <groupId>dom4j</groupId>
    <artifactId>dom4j</artifactId>
    <version>1.6.1</version>
</dependency>
```

**Comment by FilipJirsak** [comment]
There are two groupId: `dom4j` for version 1.6.1 and older, and `org.dom4j` for version 2 and newer. There is old groupId `dom4j` but new version in the error message above.

**Comment by FilipJirsak** [comment]
I think there must be another place in your pom.xml where is defined dependency on `dom4j:dom4j:2.1.1`. Maybe version is defined by a variable which is used for both `dom4j:dom4j` and `org.dom4j:dom4j`? Can you show the whole `pom.xml` file?

**Comment by xvitcoder** [comment]
You are right, I did a dependency check and I found out that hibernate-validation which is used by spring-data, is using dom4j 1.6.1

so I have excluded it and it works now

```xml
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-data-jpa</artifactId>
    <exclusions>
        <exclusion>
            <groupId>dom4j</groupId>
            <artifactId>dom4j</artifactId>
        </exclusion>
    </exclusions>
</dependency>
```

thank you for pointing out
