### ISSUE TITLE
A typo in the sample code for writing to a file

### ISSUE THREAD

**Issue by nikolaybespalov** [dom4j/dom4j#62]
A typo in the sample code for writing to a file on the site https://dom4j.github.io/

```java
// lets write to a file
try (FileWriter fileWiter = new FileWriter("output.xml")) {
    XMLWriter writer = new XMLWriter(fileWriter);
    writer.write( document );
    writer.close();
}
```
A typo in the name "fileWiter".

**Comment by harkue** [comment]
This typo is not in source code of this repo, and it seem only can be corrected by @FilipJirsak .

**Comment by FilipJirsak** [comment]
Actually, the issue of web pages, see https://github.com/dom4j/dom4j.github.com/issues/5.
