### ISSUE TITLE
element "input" must be end of "</input>"

### ISSUE THREAD

**Issue by 908875137** [dom4j/dom4j#68]
The element type "input" must be terminated by a matching closing tag "</input>".Nested exception: the element type "input" must be terminated by the matching end tag "</input>".

元素类型 "input" 必须由匹配的结束标记 "</input>" 终止。 Nested exception: 元素类型 "input" 必须由匹配的结束标记 "</input>" 终止。

How can I do?  where can I stop this check? Or pass this element

**Comment by FilipJirsak** [comment]
This error does not come from dom4j, it is caused by XML parser. The XML document you are parsing must be well-formed.

**Comment by carlosame** [comment]
In fact the `<input>` tag has no end tag, so unless we are talking about a non-html namespace, this issue probably has to do with some DTD problem. It could be related to recent changes in the library, but as the OP won't even tell us which version of dom4j he is using, he deserves the issue being closed.

**Comment by carlosame** [comment]
Nevermind, this specific error is caused by bad xml.

**Comment by 908875137** [comment]
Thank you. Finally, I use Google guava replace all <input> to <input/>.  Then do others.  
But I suggest adding a function to custom special xml parser.

**Comment by FilipJirsak** [comment]
@908875137 You can use any parse you choose. `org.dom4j.io.SAXReader` accepts any `org.xml.sax.XMLReader` in constructor. You can pass any `javax.xml.stream.XMLEventReader` into `org.dom4j.io.STAXEventReader.readDocument()` method.  Or you can use both `XPPReader` and `XPP3Reader`.

Dom4j is XML library. May be you are working with HTML. HTML can be serialized to XML as XHTML. The HTML serialization can't be parsed directly by XML  parser. There are some libraries which can convert HTML to XML - for example [The Validator.nu HTML Parser](https://about.validator.nu/htmlparser/), [JSoup](https://jsoup.org/) or [JTidy](http://jtidy.sourceforge.net/).

**Comment by 908875137** [comment]
Thank you , I have no problems now.
