### ISSUE TITLE
Maven pom.xml is missing the license

### ISSUE THREAD

**Issue by JD-CSTx** [dom4j/dom4j#71]
Your maven pom.xml is missing the license, like this:
```
<licenses>
    <license>
      <name>LGPL 2.1</name>
      <url>http://www.gnu.org/licenses/lgpl-2.1.html</url>
      <comments>See discussion at http://whatever.com/license for more details.</comments>
      <distribution>repo</distribution>
    </license>
  </licenses>
```

**Comment by cabb** [comment]
Can this closed?
Because there is no pom.xml anymore and the license is clearly specified.

**Comment by JD-CSTx** [comment]
So, there are no Maven releases anymore, is that correct?

**Comment by JD-CSTx** [comment]
Saw it: https://search.maven.org/artifact/org.dom4j/dom4j/2.1.3/jar
It is there, and the pom.xml with the correct license info is generated. Looks good. I'm happy.
